services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - SERVER_ADDRESS=0.0.0.0:80
      - SERVER_PORT=80
      - DB_USER=backenduser
      - DB_PASSWORD=superStrongPassword
      - DB_HOST=postgres
      - JAEGER_HOST=jaeger      
      - JAEGER_PORT=6831
      - DB_PORT=5432 
      - DB_NAME=db
    depends_on:
      migrations:
        condition: service_completed_successfully
      jaeger:
        condition: service_started

  postgres:
    image: postgres:16.6
    environment:
      - POSTGRES_USER=backenduser
      - POSTGRES_PASSWORD=superStrongPassword
      - POSTGRES_DB=db
    ports:
      - "5432:5432" # change this
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U backenduser -d db"]
      interval: 1s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  migrations:
    image: ghcr.io/kukymbr/goose-docker:3.24.1
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=host=postgres user=backenduser password=superStrongPassword dbname=db sslmode=disable
    volumes:
      - ./migrations:/migrations/
    depends_on:
      postgres:
        condition: service_healthy

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"

volumes:
  postgres_data:
